Feature/forgot password
wisemen-digital/nestjs-project-template pull request #12
Opened 2024-01-23 16:05 UTC by ekrembiler

2024-01-25 06:56 UTC, jorenvandeweyer requested changes

2024-01-25 06:56 UTC, jorenvandeweyer commented on src/modules/users/controllers/user.controller.ts
> +@Public()
ik denk niet da alle user calls public moeten zijn?

2024-01-25 06:56 UTC, jorenvandeweyer commented on src/modules/users/controllers/user.controller.ts
> +@Public()
doet dit uberhaubt wel iets?

2024-01-25 06:56 UTC, jorenvandeweyer commented on templates/content/forgot-password.content.ts
mss hier al content includen?

2024-01-25 06:56 UTC, jorenvandeweyer commented on src/modules/users/controllers/user.controller.ts
> +    await this.userService.forgotPassword(user.email)
`await this.userService.forgotPassword(forgotPasswordDto.email)`

2024-01-26 09:16 UTC, SebastiaanVanspauwen commented
Paar dingen die we moeten beslissen

- Handlebars vs mjml voor mailing

- Generic translation template voor mails

- Welke mail client we nu gaan gebruiken

Ik heb in een project bijvoorbeeld dit om als er een taal bijkomt verplicht voor elke mail een vertaling bij te voegen

```
export type MailTranslation<T> = {
  [lang in typeof ACCEPTED_LANGUAGES[number]]: T
}

export interface ForgotPasswordMailType {
  subject: string
  password: {
    header: string
    body: string
  }
  button: {
    text: string
  }
}

export const forgotPasswordTranslation: MailTranslation<ForgotPasswordMailType> = { ... }

```

2024-07-04 13:18 UTC, closed without merging