Mail service implementation
wisemen-digital/nestjs-project-template pull request #26
Opened 2024-02-26 12:19 UTC by PauwelsPieter

2024-02-26 12:32 UTC, SebastiaanVanspauwen commented on src/modules/mail/clients/handlebars.client.ts
> +    const templateFile = fs.readFileSync(`${this.templateDir}${templateName}.hbs`).toString()
Handlebars voor mailing? Willen we hier niet MJML voor gebruiken?

Kan hier makkelijk styling op gemaakt worden?
MJML zet automatisch om naar alle mail clients (outlook, gmail, ...) zodat mails overal mooi gerenderd worden

2024-02-26 12:34 UTC, SebastiaanVanspauwen requested changes

2024-02-26 12:34 UTC, SebastiaanVanspauwen commented on src/modules/mail/services/mail.service.ts
> +      subject: 'Reset password',
zou de service niet alleen de sendMail moeten hebben?

Ik zou ook nog liefst vertalingstemplate hebben voor mail 🙈

2024-02-27 14:05 UTC, jorenvandeweyer requested changes

2024-02-27 14:05 UTC, jorenvandeweyer commented on src/modules/mail/renderer/mjml.renderer.ts
> +  private readonly templateDir = './src/modules/mail/templates/'
werkt dit in docker? volgens mij moeten die files expliciet overgekopieerd worden

2024-02-27 14:05 UTC, jorenvandeweyer commented on src/modules/mail/services/mail.service.ts
> +    const html = await this.mjmlRenderer.render('forgot-password', mergeObjects(ForgotPasswordTranslation.nl, {
merge object is wel iets fancy voor iets simpel wat hier gebeurd

2024-02-28 08:30 UTC, PauwelsPieter commented on src/modules/mail/services/mail.service.ts
> +    const html = await this.mjmlRenderer.render('forgot-password', mergeObjects(ForgotPasswordTranslation.nl, {
Hm, als je in je mjml via ejs diep geneste objecten hebt en je wilt een property van een object in de translation zetten en eentje hier in de service aanvullen, bv:

```
translation = {
  body: {
    button: {
      text: "Neem contact op!"
    }
  }
}

dynamicFields = {
  body: {
    button: {
      href: "https://www.google.com"
    }
  }
}
```

2024-02-28 08:31 UTC, PauwelsPieter commented on src/modules/mail/renderer/mjml.renderer.ts
> +  private readonly templateDir = './src/modules/mail/templates/'
Indeed, nice spot

2024-02-29 13:42 UTC, PauwelsPieter commented on src/modules/mail/renderer/mjml.renderer.ts
> +  private readonly templateDir = './src/modules/mail/templates/'
Door middel van 
```
"assets": [{ "include": "**/*.mjml", "outDir": "dist/src"}],
```

In `nest-cli.json` worden `.mjml` files ook in de `dist` folder ge-compiled en dus ook gecopied naar de docker container.
```
COPY --from=build --chown=nobody /app/dist dist
```

2024-02-29 14:27 UTC, jorenvandeweyer approved these changes

2024-03-04 07:16 UTC, PauwelsPieter commented
@SebastiaanVanspauwen

2024-03-04 07:22 UTC, SebastiaanVanspauwen approved these changes

2024-03-04 07:23 UTC, merged