added files
wisemen-digital/nestjs-project-template pull request #42
Opened 2024-05-08 12:39 UTC by jorenvandeweyer

2024-05-08 12:47 UTC, jorenvandeweyer commented
er staan enkele files in comment, stephen gaat maandag pg boss toevoegen dus please ignore

2024-05-08 14:25 UTC, siemenvdn requested changes

2024-05-08 14:25 UTC, siemenvdn commented on src/modules/files/dtos/create-file.dto.ts
> +  mimeType: MimeType
waarom mime-type en niet extensie?

2024-05-08 14:25 UTC, siemenvdn commented on src/modules/files/controllers/file.controller.ts
> +  @Post()
lege lijn tussen vlammen

2024-05-08 14:25 UTC, siemenvdn commented on src/modules/files/controllers/file.controller.ts
> +  @Post()
vind dit ook mooier precies 🙊 
```suggestion
  constructor (
    private readonly fileService: FileService
  ) {}
  
  @Post()
```

2024-05-08 14:25 UTC, siemenvdn commented on src/modules/files/services/file-entity.service.ts
> +    FileEntity: FileEntity,
camelcase

2024-05-08 14:25 UTC, siemenvdn commented on src/modules/files/services/file.service.ts
> +  async getTemporarilyUrl (file: File): Promise<string> {
taalvout
```suggestion
  async getTemporaryUrl (file: File): Promise<string> {
```

2024-05-08 14:25 UTC, siemenvdn commented on src/modules/files/services/file.service.ts
> +    await this.fileRepository.save(file)
.confirmUpload toevoegen in fileRepository

2024-05-08 14:25 UTC, siemenvdn commented on src/modules/files/services/file-entity.service.ts
> +    const existingFileEntitys = await this.fileEntityRepository.find({
findBy

2024-05-08 14:25 UTC, siemenvdn commented on src/modules/files/services/s3.service.ts
> +  public async getTemporarilyDownloadUrl (
taalvout
```suggestion
  public async getTemporaryDownloadUrl (
```

2024-05-08 14:25 UTC, siemenvdn commented on src/modules/files/services/s3.service.ts
> +    mimeType?: string,
is deze geen enum

2024-05-08 14:25 UTC, siemenvdn commented on src/modules/files/services/s3.service.ts
> +    return await getSignedUrl(this.s3, command, { expiresIn: expiresIn ?? 1800 })
misschien private readonly property met default expiresIn / in .env?

2024-05-08 14:25 UTC, siemenvdn commented on src/modules/files/transformers/file.transformer.ts
> +  @ApiProperty({ type: 'string', nullable: true })
enum?

2024-05-08 14:25 UTC, siemenvdn commented on src/modules/files/transformers/file.transformer.ts
apiproperties uitschrijven

2024-05-08 14:25 UTC, siemenvdn commented on src/modules/files/transformers/file.transformer.ts
> +  transform (fileMorph: FileEntity): FileTransformerType {
waarom noemt die fileMorph??

2024-05-08 14:25 UTC, siemenvdn commented on src/modules/files/transformers/file.transformer.ts
> +    if (fileMorph.file == null) throw new Error('File is not loaded on FileEntity')
debug help dingetje: 
```suggestion
    if (fileMorph.file == null) throw new Error('file.transformer - File is not loaded on FileEntity')
```

2024-05-08 14:25 UTC, siemenvdn commented on src/modules/files/transformers/file-created.transformer.ts
apiproperties ontbreken

2024-05-08 14:55 UTC, Kobe-Kwanten requested changes

2024-05-08 14:55 UTC, Kobe-Kwanten commented on src/modules/files/controllers/file.controller.ts
> +  @HttpCode(302)
Is dit voldoende om een redirect te triggeren via de response?

Nest biedt iets aan om zelf minder headers te moeten zetten enzovoort, tenzij dat nog gewenst is natuurlijk. Maar dat bleek niet onmiddellijk nodig te zijn.
Ik had het in Trixxa gedaan via:

```
@Redirect()
 async getFileDownload (
    @Param('file') file: string
  ): Promise<HttpRedirectResponse> {
    const downloadUrl = await this.fileService.getDownloadUrl(file)
    return {
      statusCode: HttpStatus.FOUND,
      url: downloadUrl
    }
  }
```

2024-05-08 14:55 UTC, Kobe-Kwanten commented on src/modules/files/controllers/file.controller.ts
> +    const file = await this.fileService.findOneOrFail({ uuid: fileUuid })
waarom zit dit in 2 stappen?

2024-05-08 14:55 UTC, Kobe-Kwanten commented on src/modules/files/entities/file-entity.entity.ts
> +export class FileEntity {
waarom noemt dit file entity en niet gewoon file?

2024-05-08 14:55 UTC, Kobe-Kwanten commented on src/modules/files/dtos/create-file-entity.dto.ts
> +export class CreateFileEntityDto {
deze wordt niet gebruikt in de file controller?

2024-05-08 14:55 UTC, Kobe-Kwanten commented on src/modules/files/entities/file.entity.ts
> +export class File {
wat is het verschil tussen `File` en `FileEntity` dat is wel verwarrende benaming

2024-05-08 14:55 UTC, Kobe-Kwanten commented on src/modules/files/entities/file-entity.entity.ts
> +  @Column({ type: 'uuid' })
geen index hierop?

2024-05-08 14:55 UTC, Kobe-Kwanten commented on src/modules/files/entities/file-entity.entity.ts
> +  @Column({ type: 'uuid' })
geen index op een foreign key?

2024-05-08 14:55 UTC, Kobe-Kwanten commented on src/modules/files/entities/file-entity.entity.ts
> +  @Column({ type: 'varchar' })
waarom is collectionName een varchar? wat soort collection names moet ik me voorstellen?

2024-05-08 14:55 UTC, Kobe-Kwanten commented on src/modules/files/entities/file.entity.ts
> +  @DeleteDateColumn({ precision: 3, nullable: true })
nullable moet je niet expliciet aangeven, dat is altijd zo op een delete date column

2024-05-08 14:55 UTC, Kobe-Kwanten commented on src/modules/files/entities/file-entity.entity.ts
> +export class FileEntity {
waarom is file softremoveable maar fileentity niet?

2024-05-08 14:55 UTC, Kobe-Kwanten commented on src/modules/files/entities/file.entity.ts
> +  @Column({ type: 'varchar' })
gewoon name? dit is toch de file zelf `file.fileName` vs `file.name`

2024-05-08 14:55 UTC, Kobe-Kwanten commented on src/modules/files/entities/file.entity.ts
> +  url: string
is dit niet optioneel want dit is niet altijd ingevuld in de database?

2024-05-08 14:55 UTC, Kobe-Kwanten commented on src/modules/files/entities/file.entity.ts
> +  mimeType: string | null
waarom is mimetype een varchar als de enum bestaat?

2024-05-08 14:55 UTC, Kobe-Kwanten commented on src/modules/files/helpers/file-joiner.ts
> +    collectionName: keyof T,
lijkt me niet de `collectionName` maar een `propertyName`

2024-05-08 14:55 UTC, Kobe-Kwanten commented on src/modules/files/helpers/file-joiner.ts
> +        `${entityTypeName}.${fileEntityAlias}`,
duplicate code

2024-05-08 14:55 UTC, Kobe-Kwanten commented on src/modules/files/helpers/file-joiner.ts
> +    const fileAlias = `${collectionNameString}File`
deze alias is niet voldoende als je meerdere keren wilt joinen op hetzelfde type,
kijk naar de trixxa file joiner die met een counter werkt om dit te voorkomen

2024-05-08 14:55 UTC, Kobe-Kwanten commented on src/modules/files/helpers/file-joiner.ts
> +    // Conditionally adding join and where clause for filtering by entityPart
deze comment heeft niet te maken met wat hieronder staat

2024-05-08 14:55 UTC, Kobe-Kwanten commented on src/modules/files/helpers/file-joiner.ts
> +  public joinFile (
functie kan opgedeeld worden in 2 stappen
1. Join FileEntity
2. Join File

2024-05-08 14:55 UTC, Kobe-Kwanten commented on src/modules/files/jobs/remove-unused-media.job.ts
> +// /* eslint-disable @typescript-eslint/ban-types */
gecommente file?

2024-05-08 14:55 UTC, Kobe-Kwanten commented on src/modules/files/modules/file.module.ts
> +    // PGBossModule.forJobs([
gecomment?

2024-05-08 14:55 UTC, Kobe-Kwanten commented on src/modules/files/modules/file.module.ts
> +    // RemoveUnusedMediaJobHandler,
gecomment?

2024-05-08 14:55 UTC, Kobe-Kwanten commented on src/modules/files/entities/file.entity.ts
> +export class File {
Ik zou meer gaan voor `File` en `LinkedFile` of zelfs `Attachment` ofzo
`Entity` is een veelgebruikte term dus ik zou denken dat je 2 keer een `File` model hebt gemaakt per ongeluk en het 1 keer een entity hebt genoemd en de andere keer niet

2024-05-08 14:55 UTC, Kobe-Kwanten commented on src/modules/files/services/file-entity.service.ts
> +    entityType: string
ik zou wel afdwingen wat voor soort collections en entities toegelaten zijn

2024-05-08 14:55 UTC, Kobe-Kwanten commented on src/modules/files/services/file-entity.service.ts
> +    FileEntity: FileEntity,
verwarrende naamgeving, lowercase

2024-05-08 14:55 UTC, Kobe-Kwanten commented on src/modules/files/services/file-entity.service.ts
> +    return await this.fileEntityRepository.save(file)
hier kan je insert doen en de file returnen
de uuid wordt ook op de file gezet bij een insert

2024-05-08 14:55 UTC, Kobe-Kwanten commented on src/modules/files/services/file-entity.service.ts
> +    const updated = this.fileEntityRepository.merge(
de repo is verantwoordelijk voor het mergen?
zou je niet gewoon instellen wat in de dto zit

2024-05-08 14:55 UTC, Kobe-Kwanten commented on src/modules/files/services/file-entity.service.ts
> +    return await this.fileEntityRepository.save(updated)
dit kan een update worden als je gewoon update wat in de dto zit

2024-05-08 14:55 UTC, Kobe-Kwanten commented on src/modules/files/services/file-entity.service.ts
> +    collectionName: keyof T,
niet collectionName mare propertyName

waarom wordt dit hier aan meegegeven?

2024-05-08 14:55 UTC, Kobe-Kwanten commented on src/modules/files/services/file-entity.service.ts
> +        collectionName: collectionNameString,
de collectionName is dus afhankelijk van een naam van een property? dat is wel funky imo

2024-05-08 14:55 UTC, Kobe-Kwanten commented on src/modules/files/services/file-entity.service.ts
> +    const existingFileEntitys = await this.fileEntityRepository.find({
`Entities` meervoud van `y` => `ie`

2024-05-08 14:55 UTC, Kobe-Kwanten commented on src/modules/files/services/file-entity.service.ts
> +    const removeFileEntitys = existingFileEntitys.filter(
`removeFileEntitys` lijkt me een functie naam, `orphanedFileEntities` lijkt me beter?

2024-05-08 14:55 UTC, Kobe-Kwanten commented on src/modules/files/services/file-entity.service.ts
> +      await this.fileEntityRepository.remove(FileEntity)
1 voor 1 ipv een remove op uuids?

2024-05-08 14:55 UTC, Kobe-Kwanten commented on src/modules/files/services/file-entity.service.ts
> +    for (const FileEntity of removeFileEntitys ?? []) {
verwarrende naamgeving, lowercase

2024-05-08 14:55 UTC, Kobe-Kwanten commented on src/modules/files/services/file-entity.service.ts
> +    for (const dto of dtos) {
1 voor 1 updaten en createn?

2024-05-08 14:55 UTC, Kobe-Kwanten commented on src/modules/files/services/file-entity.service.ts
> +  ): Promise<void> {
niets hiervan gebeurd in een transactie?

2024-05-08 14:55 UTC, Kobe-Kwanten commented on src/modules/files/services/file.service.ts
> +    const uploadUrl = await this.s3Service.getTemporarilyUploadUrl(
`getTemporarilyUploadUrl` hernoemen naar `getTemporaryUploadUrl`?

2024-05-08 14:55 UTC, Kobe-Kwanten commented on src/modules/files/services/file.service.ts
> +    file = await this.fileRepository.save(file)
dit kan een insert zijn

2024-05-08 14:55 UTC, Kobe-Kwanten commented on src/modules/files/services/file.service.ts
> +  async getTemporarilyUrl (file: File): Promise<string> {
hernoemen naar `getTemporaryUrl` 

`Temporary` is een eigenschap van iets i.e. een temporary url
`Temporarily` is een beschrijving van hoe je iets doet / hoe iets bestaat i.e. the url exists temporarily

2024-05-08 14:55 UTC, Kobe-Kwanten commented on src/modules/files/services/file.service.ts
> +    const url = await this.s3Service.getTemporarilyDownloadUrl(
inlinen?

2024-05-08 14:55 UTC, Kobe-Kwanten commented on src/modules/files/services/file.service.ts
> +    await this.fileRepository.save(file)
dit kan een update zijn

2024-05-08 14:55 UTC, Kobe-Kwanten commented on src/modules/files/services/s3.service.ts
> +    private readonly configService: ConfigService
is dit niet gewoon ... de `Config`? spijtige benaming van Nest 😞

2024-05-08 14:55 UTC, Kobe-Kwanten commented on src/modules/files/services/s3.service.ts
> +        secretAccessKey: this.configService.getOrThrow('S3_SECRET_KEY', '')
moet bij `getOrThrow` wel een 2de parameter staan?

2024-05-08 14:55 UTC, Kobe-Kwanten commented on src/modules/files/services/s3.service.ts
> +  public async getTemporarilyDownloadUrl (
`getTemporaryDownloadUrl`
of `createTemporaryDownloadUrl`
of `reserveTemporaryDownloadUrl`
die vertellen misschien iets meer als `get`

2024-05-08 14:55 UTC, Kobe-Kwanten commented on src/modules/files/services/s3.service.ts
> +    expiresIn?: number
welke unit? eens kijken naar Maarten zijn coole `Quantities` ook pas nog over bijgeleerd uit mn nieuwste boek

2024-05-08 14:55 UTC, Kobe-Kwanten commented on src/modules/files/services/s3.service.ts
> +  public async getTemporarilyUploadUrl (
`getTemporaryUploadUrl`, `createTemporaryUploadUrl`, `reserveTemporaryUploadUrl`

2024-05-08 14:55 UTC, Kobe-Kwanten commented on src/modules/files/services/s3.service.ts
> +  public async upload (fileUuid: string, body: Buffer): Promise<void> {
is `fileUuid` niet algemener `fileName`?

2024-05-08 14:55 UTC, Kobe-Kwanten commented on src/modules/files/services/s3.service.ts
> +  public async upload (fileUuid: string, body: Buffer): Promise<void> {
is `body` niet een beetje technology leaking, `content` past misschien beter

2024-05-08 14:55 UTC, Kobe-Kwanten commented on src/modules/files/services/s3.service.ts
> +  public async uploadStream (key: string, stream: Readable): Promise<void> {
is `key` niet `fileName`?

2024-05-08 14:55 UTC, Kobe-Kwanten commented on src/modules/files/services/s3.service.ts
> +  public async list (fileUuid: string): Promise<ListObjectsV2Output['Contents']> {
is `fileUuid` niet `fileName`?

2024-05-08 14:55 UTC, Kobe-Kwanten commented on src/modules/files/services/s3.service.ts
> +  public async list (fileUuid: string): Promise<ListObjectsV2Output['Contents']> {
deze return type is wel zeer S3-ich, is er iets waar we het naar kunnen mappen waarvoor we het gebruiken?

2024-05-08 14:55 UTC, Kobe-Kwanten commented on src/modules/files/services/s3.service.ts
> +  public async delete (fileUuid: string): Promise<void> {
is `fileUuid` niet `fileName`?

2024-05-08 14:55 UTC, Kobe-Kwanten commented on src/modules/files/services/s3.service.ts
> +  private createKey (fileUuid: string): string {
is `fileUuid` niet `fileName`?

2024-05-08 14:55 UTC, Kobe-Kwanten commented on src/modules/files/services/s3.service.ts
> +  private createKey (fileUuid: string): string {
is `createKey` niet `createFilePath`?

2024-05-08 14:55 UTC, Kobe-Kwanten commented on src/modules/files/subscribers/file.subscriber.ts
> +  async afterLoad (media: File): Promise<void> {
bij alle loads van een file ga je s3 aanspreken?
bijvoorbeeld dus ook wanneer je orphaned files gaat zoeken om ze te verwijderen?

2024-05-08 14:55 UTC, Kobe-Kwanten commented on src/modules/files/subscribers/file.subscriber.ts
> +    await this.s3Service.delete(event.entityId)
is dit de plaats voor de remove? kan je dit transactioneel garanderen?

2024-05-08 14:55 UTC, Kobe-Kwanten commented on src/modules/files/tests/file.e2e.test.ts
> +  describe('Create file', () => {
testen opsplitsen per route?

2024-05-08 14:55 UTC, Kobe-Kwanten commented on src/modules/files/tests/file.e2e.test.ts
> +        .post('/file')
ik ben wel fan geworden om de route als constante / functie te definiëren indien de route zou wijzigen

2024-05-08 14:55 UTC, Kobe-Kwanten commented on src/modules/files/tests/file.e2e.test.ts
> +    it('should return 200', async () => {
om je eigen post aan te kaarten zou je hier `deletes a file` van maken

2024-05-08 14:55 UTC, Kobe-Kwanten commented on src/modules/files/transformers/file.transformer.ts
> +export class FileTransformerType {
`FileResponse` of `FileView`?

2024-05-08 14:55 UTC, Kobe-Kwanten commented on src/modules/files/transformers/file.transformer.ts
> +  fileName: string
`name`?

2024-05-08 14:55 UTC, Kobe-Kwanten commented on src/modules/files/transformers/file.transformer.ts
> +  transform (fileMorph: FileEntity): FileTransformerType {
wat is een `fileMorph`?

2024-05-09 18:07 UTC, jorenvandeweyer commented on src/modules/files/transformers/file.transformer.ts
> +    if (fileMorph.file == null) throw new Error('File is not loaded on FileEntity')
stack trace

2024-05-09 19:11 UTC, jorenvandeweyer commented on src/modules/files/services/s3.service.ts
> +  private createKey (fileUuid: string): string {
files worden in S3 opgeslagen met hun uuid als bestandsnaam.

2024-05-09 19:11 UTC, jorenvandeweyer commented on src/modules/files/services/s3.service.ts
> +  public async delete (fileUuid: string): Promise<void> {
nee want die worden met hun uuid in S3 opgeslagen

2024-05-09 19:17 UTC, jorenvandeweyer commented on src/modules/files/services/s3.service.ts
> +  public async list (fileUuid: string): Promise<ListObjectsV2Output['Contents']> {
nog nergens geimplementeerd, kga deze comment skippen

2024-05-09 19:18 UTC, jorenvandeweyer commented on src/modules/files/services/s3.service.ts
> +  private createKey (fileUuid: string): string {
bij S3 spreekt men over keys, file paths bestaan daar niet echt. Ik zou dus binnen deze service die terminology aanhouden.

2024-05-09 19:20 UTC, jorenvandeweyer commented on src/modules/files/transformers/file.transformer.ts
wat bedoel je?

2024-05-09 19:22 UTC, jorenvandeweyer commented on src/modules/files/services/file.service.ts
> +    const url = await this.s3Service.getTemporarilyDownloadUrl(
wat bedoel je?

2024-05-09 19:33 UTC, jorenvandeweyer commented on src/modules/files/controllers/file.controller.ts
> +  @HttpCode(302)
vreemde headers die hier ingesteld worden inderdaad

2024-05-09 19:33 UTC, jorenvandeweyer commented on src/modules/files/controllers/file.controller.ts
> +  @HttpCode(302)
@PauwelsPieter @JonasVannieuwenhuijsen waarom is dit hier?

```
const command = new GetObjectCommand({
  Bucket: this.bucketName,
  Key: this.createKey(fileUuid),
  ResponseContentType: mimeType ?? 'application/octet-stream',
  ResponseContentDisposition: `attachment; filename=${name}`
})
```

2024-05-09 19:34 UTC, jorenvandeweyer commented on src/modules/files/controllers/file.controller.ts
> +  @HttpCode(302)
s3 doet zet de headers zelf juist denk ik?

2024-05-09 19:35 UTC, jorenvandeweyer commented on src/modules/files/dtos/create-file-entity.dto.ts
> +export class CreateFileEntityDto {
is om mee tegen bij de createUserDto bv

2024-05-09 19:36 UTC, jorenvandeweyer commented on src/modules/files/dtos/create-file.dto.ts
> +  mimeType: MimeType
@JonasVannieuwenhuijsen @PauwelsPieter Waarom slaan jullie de extensie niet op?

@siemenvdn waarom zouden we de extensie apart opslaan?

2024-05-09 19:36 UTC, jorenvandeweyer commented on src/modules/files/entities/file-entity.entity.ts
> +export class FileEntity {
Ik vermoed zodat die nog gedelete kunnen worden uit S3

2024-05-09 19:37 UTC, jorenvandeweyer commented on src/modules/files/entities/file-entity.entity.ts
> +export class FileEntity {
is de link tussen een file en een entity, het noemde eerste "fileMorph"

2024-05-09 19:37 UTC, jorenvandeweyer commented on src/modules/files/entities/file-entity.entity.ts
> +  @Column({ type: 'varchar' })
@PauwelsPieter @JonasVannieuwenhuijsen waarvoor gebruikte jullie dit weer?

2024-05-09 19:38 UTC, jorenvandeweyer commented on src/modules/files/entities/file.entity.ts
> +  isUploadConfirmed: boolean
ik vind confirmed misschien beter, want er word niet effectief  gechecked of dit effectief geupload is.

2024-05-09 19:44 UTC, jorenvandeweyer commented on src/modules/files/services/file-entity.service.ts
> +    entityType: string
dus voor elk model in de DB moet er een enum value aangemaakt worden?

2024-05-09 19:47 UTC, jorenvandeweyer commented on src/modules/files/jobs/remove-unused-media.job.ts
> +// /* eslint-disable @typescript-eslint/ban-types */
voor jonas

2024-05-09 20:06 UTC, jorenvandeweyer commented on src/modules/files/entities/file.entity.ts
> +export class File {
renamed naar FileLink

2024-05-09 20:10 UTC, jorenvandeweyer commented on src/modules/files/tests/file.e2e.test.ts
> +        .post('/file')
moeten we eens op de circle bespreken

2024-05-09 20:10 UTC, jorenvandeweyer commented on src/modules/files/tests/file.e2e.test.ts
> +  describe('Create file', () => {
bedoel je 1 typescript file per route? of hoe opsplitsen?

2024-05-10 09:51 UTC, jorenvandeweyer commented on src/modules/files/entities/file-entity.entity.ts
> +  @Column({ type: 'varchar' })
aangepast naar property en entityPart

2024-05-10 09:52 UTC, jorenvandeweyer commented on src/modules/files/services/file-entity.service.ts
> +    entityType: string
ik ga dit resolven en als issue aanmaken, TBD

2024-05-10 09:54 UTC, jorenvandeweyer commented on src/modules/files/services/file-entity.service.ts
> +    const removeFileEntitys = existingFileEntitys.filter(
helemaal opnieuw geschreven. Delete & upsert lijkt mij veel logischer.

2024-05-10 10:00 UTC, jorenvandeweyer commented on src/modules/files/dtos/create-file.dto.ts
> +  mimeType: MimeType
ik heb er een discussion van gemaakt #44

2024-05-10 10:02 UTC, jorenvandeweyer commented on src/modules/files/controllers/file.controller.ts
> +  @HttpCode(302)
Ik ga dit testen en fixen in de volgende PR

Ik maak er een issue voor aan.

2024-05-15 01:31 UTC, siemenvdn requested changes

2024-05-15 01:31 UTC, siemenvdn commented on src/modules/files/helpers/file-joiner.ts
> +export class FileJoiner2<T extends ObjectLiteral> {
what happened to FileJoiner1

2024-05-15 01:31 UTC, siemenvdn commented on src/modules/files/helpers/file-joiner.ts
> +  ): FileJoiner2<T> {
```suggestion
  ): this {
```

2024-05-15 01:31 UTC, siemenvdn commented on src/modules/files/helpers/file-joiner.ts
> +  public joinFile (property: string, entityPart: string, alias?: string): FileJoiner2<T> {
```suggestion
  public joinFile (property: string, entityPart: string, alias?: string): this {
```

2024-05-15 01:31 UTC, siemenvdn commented on src/modules/files/helpers/file-joiner.ts
> +  public joinFiles (property: string, entityPart: string, alias?: string): FileJoiner2<T> {
```suggestion
  public joinFiles (property: string, entityPart: string, alias?: string): this {
```

2024-05-15 01:31 UTC, siemenvdn commented on src/modules/files/entities/file.entity.ts
> +  mimeType: MimeType | null
👎🏼

2024-05-15 01:31 UTC, siemenvdn commented on src/modules/files/services/file.service.ts
> +  async getTemporarilyUrl (file: File): Promise<string> {
nogsteeds vout

2024-05-15 01:31 UTC, siemenvdn commented on src/modules/files/services/s3.service.ts
> +    private readonly configService: ConfigService
we zouden `as` kunnen gebruiken en onze eigen conventies aanhouden 🙈

2024-05-15 01:31 UTC, siemenvdn commented on src/modules/files/tests/builders/create-file-dto.builder.ts
> +    this.dto.name = 'test.png'
```suggestion
    this.dto.name = 'test'
```
😇

2024-05-15 01:31 UTC, siemenvdn commented on src/modules/files/transformers/file-created.transformer.ts
> +}
```suggestion
const createFileResponse: ApiResponse = {
    status: 201,
    description: 'Successfully created file',
    type: CreateFileResponse
}
```

2024-05-15 16:01 UTC, jorenvandeweyer commented on src/modules/files/entities/file.entity.ts
> +  mimeType: MimeType | null
?

2024-05-15 16:01 UTC, jorenvandeweyer commented on src/modules/files/entities/file.entity.ts
> +  mimeType: MimeType | null
wat bedoel je?

2024-05-15 16:01 UTC, siemenvdn commented on src/modules/files/entities/file.entity.ts
> +  mimeType: MimeType | null
vind mimetype echt een gekke keuze over extension

2024-05-15 16:02 UTC, siemenvdn commented on src/modules/files/entities/file.entity.ts
> +  mimeType: MimeType | null
check de discussion

2024-05-15 16:02 UTC, jorenvandeweyer commented on src/modules/files/helpers/file-joiner.ts
> +export class FileJoiner2<T extends ObjectLiteral> {
kheb die verwijderd

2024-05-15 16:03 UTC, jorenvandeweyer commented on src/modules/files/tests/builders/create-file-dto.builder.ts
> +    this.dto.name = 'test.png'
ja ik twijfel hierover, dan moeten we bij het downloaden de ext via de mimetype resolven

2024-05-15 16:03 UTC, jorenvandeweyer commented on src/modules/files/tests/builders/create-file-dto.builder.ts
> +    this.dto.name = 'test.png'
Kunnen we deze discussie verder voeren in de discussions op github? @siemenvdn

2024-05-15 16:09 UTC, jorenvandeweyer commented on src/modules/files/entities/file.entity.ts
> +  mimeType: MimeType | null
oke, ik verpaats naar discussion

2024-05-21 14:19 UTC, jorenvandeweyer commented on src/modules/files/entities/file-link.entity.ts
> +  @Index()
Hoe bedoel je?

2024-05-21 14:19 UTC, merged