Created the PGBoss job
wisemen-digital/nestjs-project-template pull request #47
Opened 2024-05-14 14:58 UTC by stephenhenckaerts

2024-05-14 15:02 UTC, maartensijmkens approved these changes

2024-05-15 07:20 UTC, PauwelsPieter commented on src/modules/jobs/modules/job.module.ts
> +    ])
Ik ben niet mee waarom je deze Module met entities hebt aangemaakt?

2024-05-15 07:33 UTC, maartensijmkens requested changes

2024-05-15 07:33 UTC, maartensijmkens commented on src/modules/jobs/types/job-data.type.ts
> +}
is het nodig om `retries`, `priority`, `createdAt` en `queueName` bij te houden? Dit zijn al kolommen op de Job tabel, dus lijkt mij duplication.

en waarom `customerUuid`? Toch niet elke job heeft dit?

```suggestion
export interface JobData {
  classData: unknown
  className: string
}
```

2024-05-15 07:33 UTC, maartensijmkens commented on src/modules/jobs/entities/job.entity.ts
> +export class Job extends JobBase {}
wat doet dit tov JobBase?

2024-05-15 07:52 UTC, jorenvandeweyer commented on src/modules/users/jobs/example.job.ts
> +    console.log(`Received job with message: ${job.data.message}`)
linting issue

2024-05-15 07:52 UTC, jorenvandeweyer commented on src/modules/users/jobs/example.job.ts
> +}
wanneer gebruiken we kubernetes cronjobs, nestjs cronjobs of pgboss cronjobs?

2024-05-15 07:58 UTC, jorenvandeweyer requested changes

2024-05-15 07:58 UTC, jorenvandeweyer commented on src/modules/jobs/types/job-data.type.ts
> +}
dat lijkt me niet juist, eerder zoals maarten zegt

2024-05-15 07:58 UTC, jorenvandeweyer commented on src/app.module.ts
> +    ArchivedJob,
waarom staat dit bij de imports?

2024-05-15 09:44 UTC, stephenhenckaerts commented on src/modules/jobs/modules/job.module.ts
> +    ])
Ik ben niet 100% mee welke entities hier neergeschreven worden. Ik heb het gevoel dat alle entities die gedefinieerd worden in de modulle  hier moeten toegevoegd worden.

2024-05-15 09:45 UTC, stephenhenckaerts commented on src/modules/jobs/entities/job.entity.ts
> +export class Job extends JobBase {}
Ge kunt idd ook de Job als base gebruiken en de archived daar vanaf erven.

2024-05-15 09:45 UTC, stephenhenckaerts commented on src/modules/users/jobs/example.job.ts
> +    console.log(`Received job with message: ${job.data.message}`)
Dit is een voorbeeld. Anders schrijf ik hier een lege functie.

2024-05-15 09:45 UTC, stephenhenckaerts commented on src/modules/users/jobs/example.job.ts
> +}
Zo doen ze het nu in Studaro. Ik heb het daarvan overgenomen.

2024-05-15 09:48 UTC, PauwelsPieter commented on src/modules/jobs/modules/job.module.ts
> +    ])
Je maakt een `job.entity.ts` & `archived-job.entity.ts` aan, waarom doe je dat? Waar gebruik je die?

Je defined momenteel enkel die 2 entities hier in de `job.module.ts`, maar verder doe je er niks mee...

2024-05-15 09:51 UTC, stephenhenckaerts commented on src/modules/jobs/modules/job.module.ts
> +    ])
Klopt. Dat is aan de projecten als ze hier wel of niets mee willen doen. In sommige projecten zou ge de Jobs willen opvragen en tonen aan de eindgebruiker. Dan kunt ge hier een repository voor schrijven en dan die opzoeken in de db.

2024-05-15 09:54 UTC, PauwelsPieter commented on src/modules/users/jobs/example.job.ts
> +}
Die is een nestjs cronjob die een pgboss job queued. Wat is het gewenste @jorenvandeweyer

2024-05-15 09:54 UTC, PauwelsPieter commented on src/modules/jobs/modules/job.module.ts
> +    ])
Alright, dan ben ik mee. Thanks!

2024-05-15 10:33 UTC, jorenvandeweyer commented on src/modules/users/jobs/example.job.ts
> +    console.log(`Received job with message: ${job.data.message}`)
zet dan allow console.log op zijn minst

2024-05-15 10:36 UTC, jorenvandeweyer commented on src/modules/users/jobs/example.job.ts
> +}
hangt er vanaf hoevaak en wanneer de job moet worden uitgevoerd.

Jobs die 1x per dag worden uitgevoerd -> kubernetes cronjobs

Jobs die enkele 30s moeten worden uitgevoerd gaan niet in kubernetes, daarvoor is die cron van nestjs nog we nice, MAAR dan moet dat als een aparte entrypoint uitgevoerd worden.

https://docs.nestjs.com/standalone-applications
of 
https://docs.nestjs.com/microservices/basics

2024-05-15 11:12 UTC, jorenvandeweyer requested changes
zie comments

2024-05-22 14:45 UTC, SebastiaanVanspauwen commented
Willen we hiervoor wel een package gebruiken met lage wekelijkse downloads?

2024-06-10 09:36 UTC, closed without merging