feat: Added time related decorators
wisemen-digital/nestjs-project-template pull request #48
Opened 2024-05-22 08:03 UTC by JensV5

These decorators check if the time is valid in hh:mm format and if the time is after a certain time

2024-05-22 08:17 UTC, Kobe-Kwanten requested changes

2024-05-22 08:17 UTC, Kobe-Kwanten commented on src/utils/validators/is-after-time.validator.ts
> +export function IsAfterTimeString (
zouden we hier een parameter aan toevoegen om het format dynamisch te maken?
of een optie uit 2 formats ofzo?  `hh:mm` en `hh:mm:ss`

2024-05-22 08:17 UTC, Kobe-Kwanten commented on src/utils/validators/is-valid-time.validator.ts
> +    return Time.isValidTimeString(`${timeString}:00`)
idem

2024-05-22 13:19 UTC, jorenvandeweyer approved these changes

2024-06-17 10:46 UTC, JensV5 commented
To check with Kobe:
After talks with him, noticed there are validator constraints already in the time package.
Is it a possibility to wrap those in NestJS?

2024-06-17 10:46 UTC, closed without merging