add typesense search builder
wisemen-digital/nestjs-project-template pull request #49
Opened 2024-05-22 08:50 UTC by JonasVannieuwenhuijsen

2024-05-22 09:25 UTC, Kobe-Kwanten requested changes

2024-05-22 09:25 UTC, Kobe-Kwanten commented on src/modules/typesense/collections/abstract-typesense.collection.ts
> +export abstract class AbstractTypesenseCollection {
moet abstract in deze classname staan? 🤔

2024-05-22 09:25 UTC, Kobe-Kwanten commented on src/modules/typesense/collections/user.collections.ts
> +    { name: 'permissions', type: 'string[]', optional: true, facet: true }
nu is er niets dat afdwingt dat `optional: true` en `facet: true` aanwezig moeten zijn,
hebben we dat nodig?

OF gaan we toch liever naar 1 fields array waarin je aangeeft met `filterOnly: true` of het enkel een filter veld is?

2024-05-22 09:25 UTC, Kobe-Kwanten commented on src/modules/typesense/enums/typesense-collection-index.enum.ts
> +export enum TypesenseCollection {
hebben we deze nog nodig als we overstappen naar de user collection?

`new TypesenseUserCollection().name`?

2024-05-22 09:47 UTC, JonasVannieuwenhuijsen commented on src/modules/typesense/enums/typesense-collection-index.enum.ts
> +export enum TypesenseCollection {
Momenteel wordt deze enum gebruikt in de dto's voor de migrate en import trigger via api calls. Dus ik denk van wel...

2024-05-22 10:58 UTC, JonasVannieuwenhuijsen commented on src/modules/typesense/collections/user.collections.ts
> +    { name: 'permissions', type: 'string[]', optional: true, facet: true }
optional is voor aan te geven dat het nullable kan zijn enzo. Dus da is niet iets dat verplicht aanwezig moet zijn.
die facet is blijkbaar niet nodig heb ik net gezien...

2024-05-22 10:59 UTC, Kobe-Kwanten commented on src/modules/typesense/collections/user.collections.ts
> +    { name: 'permissions', type: 'string[]', optional: true, facet: true }
is er dan nog wel een verschil tussen filter en sort?

2024-05-22 11:01 UTC, JonasVannieuwenhuijsen commented on src/modules/typesense/collections/user.collections.ts
> +    { name: 'permissions', type: 'string[]', optional: true, facet: true }
ja je wilt gewoon niet dat sommige velden zoekbaar zijn, dat wanneer je bij de builder niet aangeeft wat de searchfields zijn dat je default wel de juiste velden pakt.

Maar dat kunnen we dan miss oplossen door een filterOnly toe te voegen

2024-05-22 11:02 UTC, Kobe-Kwanten commented on src/modules/typesense/collections/user.collections.ts
> +    { name: 'permissions', type: 'string[]', optional: true, facet: true }
of misschien gewoon default search fields instellen? beiden zouden gaan

2024-05-22 14:38 UTC, SebastiaanVanspauwen commented on src/modules/typesense/builder/search-params.builder.ts
> +      page: this.offset,
Kunnen we hier ook niet offset en limit gebruiken?
https://typesense.org/docs/26.0/api/search.html#pagination-parameters

2024-06-03 08:46 UTC, jorenvandeweyer approved these changes

2024-06-03 08:46 UTC, jorenvandeweyer commented on src/utils/pagination/keyset/paginated.transformer.ts
> +        next: this.getLastTimestamp(infiniteScrollItems.items, timestampKey)?.toISOString()
FYI: dit moet wel anders geimplementeerd worden

timestamp+primarykey

Doen we beter in een volgende PR, kan je hiervoor een issue aanmaken?

2024-06-03 08:46 UTC, jorenvandeweyer commented on src/modules/users/tests/user.e2e.test.ts
waarom comment?

2024-06-03 08:46 UTC, jorenvandeweyer commented on src/modules/users/services/user.service.ts
> +    })
soort helper functie van maken

2024-06-04 07:19 UTC, JonasVannieuwenhuijsen commented on src/modules/users/tests/user.e2e.test.ts
Ik moest hier nog de manier implementeren dat we niet meer werken met subscribers, maar dat de typesense import gebeurt in de service zelf

2024-06-16 16:53 UTC, siemenvdn approved these changes

2024-06-16 19:01 UTC, jorenvandeweyer approved these changes

2024-06-17 09:58 UTC, Kobe-Kwanten approved these changes

2024-06-17 13:11 UTC, merged