Update the users role
wisemen-digital/nestjs-project-template pull request #58
Opened 2024-06-18 11:21 UTC by stephenhenckaerts

2024-06-18 11:32 UTC, jorenvandeweyer approved these changes

2024-07-06 07:35 UTC, JonasVannieuwenhuijsen requested changes

2024-07-06 07:35 UTC, JonasVannieuwenhuijsen commented on src/modules/users/services/user.service.ts
> +    })
Aanpassen naar de nieuwe vorm van transactions

2024-07-22 07:16 UTC, JonasVannieuwenhuijsen approved these changes

2024-08-06 11:07 UTC, jorenvandeweyer approved these changes

2024-08-06 11:13 UTC, merged