add new test files and add pnpm test:pipeline command
wisemen-digital/nestjs-project-template pull request #69
Opened 2024-07-07 14:00 UTC by siemenvdn

https://github.com/wisemen-digital/devops-github-actions/issues/7

2024-07-14 18:54 UTC, jorenvandeweyer reviewed
gaan we niet meer zo doen?

2024-07-15 20:39 UTC, jonasbeckers requested changes

2024-07-15 20:39 UTC, jonasbeckers commented on src/modules/users/tests/user.e2e.test.ts
> +    ({ app, moduleRef, dataSource } = await testSetup())
Should this not use `globalTestSetup` since the user module uses typesense by default?

2024-07-16 08:40 UTC, siemenvdn commented on src/modules/users/tests/user.e2e.test.ts
> +    ({ app, moduleRef, dataSource } = await testSetup())
nee, globalTestSetup gaat worden gegeven aan de functie die vanuit de scripts word aangeroepen; deze initialiseert Typesense en de database

2024-07-17 07:33 UTC, jorenvandeweyer approved these changes

2024-07-22 05:37 UTC, jorenvandeweyer requested changes

2024-07-22 05:37 UTC, jorenvandeweyer commented on src/utils/test-setup/global-setup.ts
> +  await mainDataSourceTest.initialize()
Datasource uit moduleRef gebruiken

2024-07-23 16:51 UTC, jonasbeckers approved these changes

2024-07-29 08:14 UTC, jorenvandeweyer requested changes

2024-07-29 08:14 UTC, jorenvandeweyer commented on src/config/sql/sources/main.ts
> +export const mainDataSourceTest = new DataSource(typeormTestConfig() as DataSourceOptions)
dit weg doen

2024-07-29 08:14 UTC, jorenvandeweyer commented on src/config/sql/sources/main.ts
> +  synchronize: true
ook helemaal niet nodig

2024-07-29 08:14 UTC, jorenvandeweyer commented on src/app.module.ts
> -          autoLoadEntities: true
revert

2024-08-05 07:31 UTC, jorenvandeweyer approved these changes

2024-08-06 11:13 UTC, merged