Improve generated docs
wisemen-digital/nestjs-project-template pull request #71
Opened 2024-07-10 13:51 UTC by jonasbeckers

- Add authentication where needed
- Use consistent naming for resources
- Add examples for dto & transformer examples

2024-07-10 13:57 UTC, nielsstinissen approved these changes

2024-07-10 15:27 UTC, siemenvdn requested changes
@ApiBearerAuth()

2024-07-10 20:01 UTC, jonasbeckers commented
@siemenvdn  using `@APIOAuth2` enables us to test authenticated calls from the swagger UI. Using `@APIBearerAuth` does not seem to have the same effect.
<img width="856" alt="Scherm­afbeelding 2024-07-10 om 21 58 29" src="https://github.com/wisemen-digital/nestjs-project-template/assets/17340005/c4b2cd32-835a-490c-a4f7-a299e4c3891b">

2024-07-14 18:51 UTC, jorenvandeweyer approved these changes

2024-07-15 20:51 UTC, merged