Feature/enforce consistency
wisemen-digital/nestjs-project-template pull request #75
Opened 2024-07-19 11:17 UTC by siemenvdn

For consistency sake, made some adjustments:

- Moved all `ApiResponse` documentation to seperate file
- Moved `cache` from utils to modules, since it has a `.module`
- Moved all `.module` files to top of folder
- Add sort on documentation Tags and Routes
- Added missing response documentation:
  - `getPermssions`
  - `getApiStatus`
  - `getHealthStatus`
- Functions on controllers are `public (async) functionName`
- Removed `@ApiQuery` decorators in `typesense.controller` and moved added `@ApiProperty` in the QueryDto
- Changed auth-type on controllers to `@ApiBearerAuth()`
- Changed pagination `DEFAULT_OFFSET` to 0

2024-07-19 11:47 UTC, jonasbeckers commented
- `@ApiBearerAuth()` should be `@ApiOAuth2([])`
- Can we remove `public` modifiers if they are not needed. I don't see the point if they are public by default.

2024-07-19 12:37 UTC, jorenvandeweyer commented
> * Can we remove `public` modifiers if they are not needed. I don't see the point if they are public by default.

I think all calls should require authentication by default.

2024-07-22 06:53 UTC, PauwelsPieter commented on src/modules/permissions/controllers/permission.controller.ts
Permissie afdwingen met `@Permissions` decorator?

2024-07-22 06:53 UTC, PauwelsPieter commented on src/modules/auth/controllers/auth.controller.ts
> +  public async getUserInfo (
Permissie afdwingen met `@Permissions` decorator?

2024-07-22 06:53 UTC, PauwelsPieter commented on src/modules/files/controllers/file.controller.ts
Permissie afdwingen met `@Permissions` decorator?

2024-07-22 06:53 UTC, PauwelsPieter commented on src/modules/roles/controllers/role.controller.ts
> +    @Body() updateRoleDto: CreateRoleDto
```suggestion
    @Body() updateRoleDto: UpdateRoleDto
```
Aparte type voor update?

2024-07-22 06:53 UTC, PauwelsPieter commented on src/modules/roles/transformers/role-count.transformer.ts
> +  @ApiProperty({ type: Number, description: 'The count of the roles' })
```suggestion
  @ApiProperty({ type: Number, description: 'The count of roles' })
```

2024-07-22 06:53 UTC, PauwelsPieter commented on src/modules/users/controllers/user.controller.ts
>    async getUser (
Permissie afdwingen met `@Permissions` decorator?

2024-07-22 06:53 UTC, PauwelsPieter commented on src/modules/users/controllers/user.controller.ts
>    async updateUser (
Permissie afdwingen met `@Permissions` decorator?

2024-07-22 06:53 UTC, PauwelsPieter commented on src/modules/users/controllers/user.controller.ts
>    async deleteUser (
Permissie afdwingen met `@Permissions` decorator?

2024-07-22 06:53 UTC, PauwelsPieter commented on src/modules/users/controllers/user.controller.ts
>    async updateUserPassword (
Permissie afdwingen met `@Permissions` decorator?

2024-07-22 06:53 UTC, PauwelsPieter commented on src/modules/users/docs/user-response.docs.ts
> +  description: 'The users password has been successfully updated.'
```suggestion
  description: 'The user\'s password has been successfully updated.'
```

2024-07-22 06:53 UTC, PauwelsPieter commented on src/modules/users/guards/user.guard.ts
> +export class UserGuard implements CanActivate {
`CurrentUserGuard` noemen misschien?

2024-07-22 09:14 UTC, siemenvdn commented on src/modules/files/controllers/file.controller.ts
This PR only focuses on structure, and is not intended to change any logic

2024-07-22 09:15 UTC, siemenvdn commented on src/modules/users/controllers/user.controller.ts
>    async getUser (
This PR only focuses on structure, and is not intended to change any logic

2024-07-22 09:15 UTC, siemenvdn commented on src/modules/users/controllers/user.controller.ts
>    async updateUser (
This PR only focuses on structure, and is not intended to change any logic

2024-07-22 09:15 UTC, siemenvdn commented on src/modules/users/controllers/user.controller.ts
>    async updateUserPassword (
This PR only focuses on structure, and is not intended to change any logic

2024-07-22 09:41 UTC, siemenvdn commented on src/modules/users/guards/user.guard.ts
> +export class UserGuard implements CanActivate {
That would indicate the existence of a PastUserGuard

2024-07-23 12:16 UTC, PauwelsPieter approved these changes

2024-07-23 12:16 UTC, PauwelsPieter commented on src/modules/files/controllers/file.controller.ts
> +  @Permissions(Permission.FILE_UPDATE)
```suggestion
  @Permissions(Permission.FILE_CREATE)
```

Part of the create flow

2024-07-24 08:09 UTC, nielsstinissen requested changes

2024-07-26 13:36 UTC, Kobe-Kwanten requested changes

2024-07-26 13:36 UTC, Kobe-Kwanten commented on src/modules/auth/docs/auth-response.docs.ts
> +export const getUserInfoResponse: ApiResponseOptions = {
geen fan deze splitsing, waarom splits je dit

2024-07-26 13:36 UTC, Kobe-Kwanten commented on src/modules/auth/controllers/auth.controller.ts
> +  @ApiResponse(createTokenResponse)
je kan hier `ApiOkResponse` van maken  maar ook dat is fout want post geeft standaar 201, dus `ApiCreatedResponse`

2024-07-26 13:36 UTC, Kobe-Kwanten commented on src/modules/auth/docs/auth-response.docs.ts
> +  description: 'The user info has been successfully retrieved.',
hoe zinvol zijn deze descriptions zelfs?

2024-07-26 13:36 UTC, Kobe-Kwanten commented on src/modules/auth/docs/auth-response.docs.ts
> +export const getUserInfoResponse: ApiResponseOptions = {
constantes liefst als constante benoemen GET_USER_INFO_RESPONSE

2024-07-26 13:36 UTC, Kobe-Kwanten commented on src/modules/typesense/builder/search-params.builder.ts
> +export const DEFAULT_OFFSET = 0
idd, opsplitsing van TYPESENSE vs TYPEORM nodig

2024-07-26 13:36 UTC, Kobe-Kwanten commented on src/utils/params/uuid-param.utiil.ts
> +export const UuidParam = (param: string): ParameterDecorator => Param(param, ParseUUIDPipe)
geen arrow functie als we overal gewone functies gebruiken

2024-07-26 14:53 UTC, siemenvdn commented on src/modules/auth/docs/auth-response.docs.ts
> +export const getUserInfoResponse: ApiResponseOptions = {
Controller can get really crowded with decorator stuff if we dont seperate this imho

2024-07-26 14:59 UTC, siemenvdn commented on src/modules/auth/docs/auth-response.docs.ts
> +  description: 'The user info has been successfully retrieved.',
For now the descriptions are really simple, but for more complex responses i think they serve a purpose. Never enough documentation

2024-07-26 15:01 UTC, siemenvdn commented on src/modules/auth/controllers/auth.controller.ts
> +  @ApiResponse(createTokenResponse)
That's indeed one of the points we needed to discuss, which decorator we're going to use for responses. But I also lean towards what you propose

2024-07-26 15:05 UTC, siemenvdn commented on src/modules/auth/controllers/auth.controller.ts
> +  @ApiResponse(createTokenResponse)
For now i've changed it to ur proposal 😄

2024-07-29 07:52 UTC, JonasVannieuwenhuijsen commented on src/modules/cache/cache.module.ts
> -    // NatsModule.forRoot(),
Had deze bewust in comment gezet, zodat men weet dat men makkelijk kan switchen tussen Redis of Nats... Maar miss is er een beter manier om dat te documenteren zodat iedere backender dit weet...

2024-07-29 07:52 UTC, JonasVannieuwenhuijsen commented on src/modules/cache/services/cache.service.ts
> -    // private readonly client: NatsClient,
Idem hier, dit zijn de 2 enige dingen die je moet doe om te switchen tussen Redis en Nats

2024-07-29 14:45 UTC, Kobe-Kwanten requested changes

2024-07-29 14:45 UTC, Kobe-Kwanten commented on src/utils/params/uuid-param.utiil.ts
> +export function UuidParam (param: string): ParameterDecorator {
filename bevat `ii`

2024-07-29 14:45 UTC, Kobe-Kwanten commented on src/modules/auth/docs/auth-response.docs.ts
> +  description: 'The user info has been successfully retrieved.',
I think they can serve a purpose indeed, but not in these kinds of calls
I definitely don't think you can never have enough documentation. 
Documentation is a burden to keep up to date so I'd only use it where it brings additional value

2024-07-29 14:45 UTC, Kobe-Kwanten commented on src/modules/auth/docs/auth-response.docs.ts
> +export const getUserInfoResponse: ApiResponseOptions = {
I think you're tackling the wrong issue then. I don't think there are more decorators on a controller call than there need to be. I think there are too many calls in the controller. Hence the vertical slicing approach I suggested.
I'd rather keep information that is closely related, close.

2024-08-21 11:03 UTC, siemenvdn commented
Going to be splitting this up in smaller changes.

2024-08-21 11:03 UTC, closed without merging