Add wip vertical slices for user module
wisemen-digital/nestjs-project-template pull request #85
Opened 2024-08-14 19:10 UTC by Kobe-Kwanten

Reworked the calls to vertical slices.
Fire away.

Still need rework two calls or so...

2024-08-14 22:13 UTC, siemenvdn commented
- Put the test `seeders` and `builders` in seperate folder
- `ViewUsersQuery` → `GetUsersQuery`
	- `Get` tells me more about the route itself
- Move more functionality to ur repositories
- Why the choice to perform every Typesense operation before it’s postgres counterpart?

2024-08-14 22:24 UTC, Kobe-Kwanten commented on src/modules/users/use-cases/change-password/change-password.e2e.test.ts
> +  }
I'd rather not have to change a route in every test case

2024-08-14 22:24 UTC, Kobe-Kwanten commented on src/modules/users/use-cases/change-password/change-password.use-case.ts
> +    await this.userRepository.update({ uuid: forUserUuid.toString() }, { password: newPassword })
Why would this be usefull

2024-08-14 22:25 UTC, Kobe-Kwanten commented on src/modules/users/use-cases/change-user-name/change-user-name.e2e.test.ts
> +      .send(new ChangeUserNameCommandBuilder().build())
This is the dto

2024-08-14 22:25 UTC, Kobe-Kwanten commented on src/modules/users/use-cases/view-users/view-users.e2e.test.ts
> +    await migrateTypesense(moduleRef)
So a global setup is needed like in trixxa then, i just copied the existing tests

2024-08-14 22:26 UTC, Kobe-Kwanten commented on src/modules/users/use-cases/change-password/change-password.command.ts
Command and query pattern has well amestablished naming so i think command is acceptable, especially when we also want to move towards no response updates which is another part of the command and query pattern

2024-08-15 06:21 UTC, siemenvdn commented on src/modules/users/use-cases/change-user-name/change-user-name.e2e.test.ts
> +      .send(new ChangeUserNameCommandBuilder().build())
Yes indeed, but i think its more readable to always use a variable

2024-08-15 06:23 UTC, siemenvdn commented on src/modules/users/use-cases/change-password/change-password.e2e.test.ts
> +  }
I can't recall a single time a whole route changed when the tests were already written. And with the usage of ur IDE I don't think this argument weighs against the potential readability gain.

2024-08-15 06:25 UTC, siemenvdn commented on src/modules/users/use-cases/change-password/change-password.command.ts
Personally i think "Body" reflects it's purpose way more than "Command". Also discussed not using responses with FE and Mobile, and they were not a fan. So we will keep using responses on those routes.

2024-08-15 06:26 UTC, siemenvdn commented on src/modules/users/use-cases/view-users/view-users.e2e.test.ts
> +    await migrateTypesense(moduleRef)
A global setup is already present. Check `src/utils/test-setup/global-setup.ts`

2024-08-15 06:31 UTC, Kobe-Kwanten commented on src/modules/users/use-cases/change-password/change-password.command.ts
Sad but sure,
Still not a fan of Body though,
I don't see why the use case should be dependent on HTTP stuff.
The other way around where the controller is dependent on what the use case needs is better

2024-08-15 06:31 UTC, siemenvdn commented on src/modules/users/use-cases/change-password/change-password.use-case.ts
> +    await this.userRepository.update({ uuid: forUserUuid.toString() }, { password: newPassword })
We already discussed these benefits verbally a few times. The way of working that is used right here moves database-functionalities all over the place. If we wanted to move ORM's u would only have to edit the `.repository` file as it would contain all data-functions. Moving all those functionalities to `use-case`/`service` files does not only make it harder to possibly refactor it, but also doesn't provide a clear overview of what commands are performed on a model.

2024-08-15 06:33 UTC, Kobe-Kwanten commented on src/modules/users/use-cases/view-users/view-users.e2e.test.ts
> +    await migrateTypesense(moduleRef)
Hmmm then the package json command might not do this? I'll check

2024-08-15 06:34 UTC, Kobe-Kwanten commented on src/modules/users/use-cases/change-user-name/change-user-name.e2e.test.ts
> +      .send(new ChangeUserNameCommandBuilder().build())
I think always is a big word but saying that data you prepare should be above the action AAA is a valid argument I think for it

2024-08-15 06:35 UTC, siemenvdn commented on src/modules/users/use-cases/view-users/view-users.e2e.test.ts
> +    await migrateTypesense(moduleRef)
U don't have to call the global-setup in any tests, the pipeline only makes use of it. I refer to the PR https://github.com/wisemen-digital/nestjs-project-template/pull/69, which also links to the devops discussion

2024-08-15 06:36 UTC, Kobe-Kwanten commented on src/modules/users/use-cases/view-users/view-users.e2e.test.ts
> +    await migrateTypesense(moduleRef)
The pipeline probably does this, the package.json command i use probably didn't that's why i needed this i think, I'll check

2024-08-15 06:37 UTC, Kobe-Kwanten commented on src/modules/users/use-cases/change-password/change-password.use-case.ts
> +    await this.userRepository.update({ uuid: forUserUuid.toString() }, { password: newPassword })
Now we're talking, I'd rather not push too far with my full ideas of how I want to see this just yet tho. This PR is already a big step

I'll see where i draw the line

2024-08-15 06:40 UTC, siemenvdn commented on src/modules/users/use-cases/view-users/view-users.e2e.test.ts
> +    await migrateTypesense(moduleRef)
That's why i added `pnpm test:pipeline`, so u can locally recreate what the pipeline is doing. It's not 'probably' doing this. It **is** doing this.

2024-08-15 06:42 UTC, siemenvdn commented on src/modules/users/use-cases/change-password/change-password.use-case.ts
> +    await this.userRepository.update({ uuid: forUserUuid.toString() }, { password: newPassword })
I'd say aim for the moon, this PR already has 2000+ lines changed, those few extra lines are not gonna hurt 😛

2024-08-15 06:44 UTC, siemenvdn commented on src/modules/users/use-cases/change-password/change-password.command.ts
A use-case is written in function of the controller? Or am i missing something? I won't say it's 'dependent' on the HTTP stuff, but i'd argue it better reflects the usage. I've never heard anyone refer to a POST-route as a command.

2024-08-17 14:03 UTC, maartensijmkens commented on src/modules/users/use-cases/change-password/change-password.command.ts
I think the problem here is that this dto is used for two things: on one side it represents the expected body of the http request (see @Body in the controller class) and on the other side it defines the input parameters of the use case (thus a command)

A use-case can be triggered by a http call, but not exclusively. Other triggers could be a job, a cli command ...

In a puristic perspective this means that the body of the http request and the command passed to the use case are two distinctive dto's. However I think it would go to far to always define both seperately since they will be the same 99% of the times.

2024-08-17 14:18 UTC, maartensijmkens requested changes

2024-08-17 14:18 UTC, maartensijmkens commented on src/modules/users/use-cases/change-password/change-password.e2e.test.ts
> +  }
since every e2e test should only cover 1 route, I think it's okay to define this route on top of the file. 

However I would reserve a more general function name like `getRoute()` and make its interface as close as possible to the actual route. 
In this case:

```
function getChangePasswordRoute (userUuid: string): string {
  return `/users/${userUuid}/password`
}
```

Now one should explicity pass a `randomUuid()` or `user.uuid` as a parameter, which makes it more readable in my opinion

2024-08-21 08:24 UTC, Kobe-Kwanten commented on src/modules/users/use-cases/change-password/change-password.use-case.ts
> +    await this.userRepository.update({ uuid: forUserUuid.toString() }, { password: newPassword })
soon tm

2024-08-21 08:54 UTC, jorenvandeweyer approved these changes

2024-08-21 08:54 UTC, jorenvandeweyer commented on src/modules/users/use-cases/view-users/view-users.use-case.ts
> +  async viewUsers (query: ViewUsersQuery): Promise<ViewUsersResponse> {
expliciet public definieren

2024-08-21 09:35 UTC, SebastiaanVanspauwen commented on src/modules/users/use-cases/view-users/view-users.response.ts
> +  @ApiProperty({ type: UserIndexView })
`isArray: true` needed

2024-08-21 09:57 UTC, Kobe-Kwanten commented on src/modules/users/use-cases/view-users/view-users.use-case.ts
> +  async viewUsers (query: ViewUsersQuery): Promise<ViewUsersResponse> {
doen we als we een linter hebben die het ene of het andere forceert

2024-08-21 10:58 UTC, maartensijmkens approved these changes

2024-08-21 10:58 UTC, SebastiaanVanspauwen approved these changes

2024-08-21 10:59 UTC, siemenvdn approved these changes

2024-08-21 11:01 UTC, merged