Add api errors for user module
wisemen-digital/nestjs-project-template pull request #91
Opened 2024-08-26 17:54 UTC by Kobe-Kwanten

Another way to do errors instead of known errors.

- Follows our json spec.
- More scalable (imo) errors do not need to be defined globally but can be defined per use case.
- Generated documentation for errors (see controllers)
- Support for custom metadata in error by default
- Expect method to verify that a type of error is thrown

This PR only adds it for the user module, but the idea is to replace the known errors.

2024-08-27 08:32 UTC, jonasbeckers commented on src/utils/exceptions/api-errors/api-error-meta.decorator.ts
> +      'about the error'
Why the random `+`

2024-08-27 08:32 UTC, Kobe-Kwanten commented on src/utils/exceptions/api-errors/api-error-meta.decorator.ts
> +      'about the error'
max length

2024-08-27 08:37 UTC, jonasbeckers commented on src/utils/exceptions/http-exception.filter.ts
> +      }
- This is not the correct error format.
- it does not seem to work correct. It is always documented as 400 instead of the actual code (ex `email_already_in_use`)
<img width="600" alt="Scherm­afbeelding 2024-08-27 om 10 37 21" src="https://github.com/user-attachments/assets/e2fcc9b2-2c27-44a9-a1e4-fffbe57e32d0">

2024-08-27 08:38 UTC, Kobe-Kwanten commented on src/utils/exceptions/http-exception.filter.ts
> +      }
that's just a mistake i made in the controller

2024-08-27 08:39 UTC, jonasbeckers commented on src/modules/users/use-cases/register-user/register-user.controller.ts
> +  @ApiBadRequestResponse({ type: EmailAlreadyInUseError })
The problem with this approach is that you cannot have multiple errors documented for the same status code. It will only document the first one.

2024-08-27 08:40 UTC, Kobe-Kwanten commented on src/modules/users/use-cases/register-user/register-user.controller.ts
> +  @ApiBadRequestResponse({ type: EmailAlreadyInUseError })
Did not know that, I'll test it out

2024-08-27 08:42 UTC, Kobe-Kwanten commented on src/utils/exceptions/http-exception.filter.ts
> +      }
what about the format is not correct?

2024-08-27 08:46 UTC, jonasbeckers commented on src/modules/users/use-cases/register-user/register-user.controller.ts
> +  @ApiBadRequestResponse({ type: EmailAlreadyInUseError })
There is a workaround. We will need to make example responses like [here](https://lexigogo.development.appwi.se/api/docs#/Contracts/ContractController_create).

2024-08-27 08:48 UTC, Kobe-Kwanten commented on src/modules/users/use-cases/register-user/register-user.controller.ts
> +  @ApiBadRequestResponse({ type: EmailAlreadyInUseError })
I'll try to see what i can do, maybe make a custom decorator or something that transforms the types into examples? I'll see

2024-08-27 08:49 UTC, jonasbeckers commented on src/utils/exceptions/http-exception.filter.ts
> +      }
I think the format is [JSON API ](https://jsonapi.org/format/#errors). @jorenvandeweyer doublecheck?

2024-08-27 08:50 UTC, Kobe-Kwanten commented on src/utils/exceptions/http-exception.filter.ts
> +      }
I followed this format, what about it is not correct here?

2024-08-27 09:40 UTC, jonasbeckers commented on src/utils/exceptions/http-exception.filter.ts
> +      }
I think it needs to be wrapped like [here](https://jsonapi.org/examples/#error-objects), but not sure.

2024-08-27 09:48 UTC, Kobe-Kwanten commented on src/utils/exceptions/http-exception.filter.ts
> +      }
ok should be easy enough to fix

2024-08-27 15:19 UTC, maartensijmkens requested changes

2024-08-27 15:19 UTC, maartensijmkens commented on src/utils/exceptions/api-errors/api-error-code.decorator.ts
> +    type: code,
ik het idee erachter, maar ik weet niet of het helemaal correct is om hier `type: code` te zetten. Bij InvalidOldPasswordError krijg je bijvoorbeeld dit in de docs:

![alt text](image.png)

het is hier niet echt duidelijk dat 'invalid_old_password' een string literal is, en geen type. Hoe zou je bijvoorbeeld het verschil tussen type string en string literal 'string' documenteren?

Mogelijke oplossing is om dit als type enum te documenteren met 1 value

2024-08-27 15:19 UTC, maartensijmkens commented on src/utils/exceptions/api-errors/api-error.ts
> +  readonly abstract meta: unknown
eventueel deze class generic maken en meta type `T` geven, gelijkaardig aan `PaginatedOffsetResponse`. Weet niet of dit voordelen heeft tho

2024-08-27 15:19 UTC, maartensijmkens commented on src/utils/exceptions/api-errors/bad-request.api-error.ts
> +    type: String,
is het de standaard om dit als string en niet als int (number) te documenteren?

eventueel ook naar een `@ApiErrorStatus` extraheren?

2024-08-27 15:19 UTC, maartensijmkens commented on test/expect/expect-api-error.ts
> +        message: () => `expected ${stringifiedExpected} not to be ${stringifiedActual}`
hoezo "not to be"?

2024-08-27 15:43 UTC, maartensijmkens commented on src/utils/exceptions/api-errors/api-error.ts
> +  readonly abstract meta: unknown
(off-topic: `PaginatedOffsetResponse` mag ook een abstracte class worden zoals hier lijkt mij)

2024-08-27 18:02 UTC, Kobe-Kwanten commented on src/utils/exceptions/api-errors/api-error.ts
> +  readonly abstract meta: unknown
Het idee is dat je deze moet herdeclareren dus het lijkt me ok zoals het is voor nu. Als iemand werkelijk met `ApiError` werkt en daar een getypete meta op nodig heeft kunnen we nog verder kijken.

2024-08-27 18:11 UTC, Kobe-Kwanten commented on test/expect/expect-api-error.ts
> +        message: () => `expected ${stringifiedExpected} not to be ${stringifiedActual}`
hier moet altijd het tegenovergestelde staan
heel funky i know
maar dit is als je verwacht dat het niet hetzelfde is dus

2024-08-28 14:29 UTC, jonasbeckers approved these changes

2024-08-29 09:09 UTC, jorenvandeweyer approved these changes

2024-08-29 13:31 UTC, maartensijmkens approved these changes

2024-08-30 13:43 UTC, merged